<?php

/**
 * @file
 * Contains popin.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function popin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the popin module.
    case 'help.page.popin':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gestion de Popin') . '</p>';
      return $output;

    default:
  }
}
